<?php

namespace ContainerWlUnYtd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q3pZokService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q_3pZok' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q_3pZok'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AcceuilController::delete' => ['privates', '.service_locator.Vv3rbHE.App\\Controller\\AcceuilController::delete()', 'getAcceuilControllerdeleteService', true],
            'App\\Controller\\AcceuilController::edit' => ['privates', '.service_locator.Vv3rbHE.App\\Controller\\AcceuilController::edit()', 'getAcceuilControllereditService', true],
            'App\\Controller\\AcceuilController::index' => ['privates', '.service_locator.D1r9Q3..App\\Controller\\AcceuilController::index()', 'getAcceuilControllerindexService', true],
            'App\\Controller\\AcceuilController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\AcceuilController::new()', 'getAcceuilControllernewService', true],
            'App\\Controller\\AcceuilController::show' => ['privates', '.service_locator.wQtEMKU.App\\Controller\\AcceuilController::show()', 'getAcceuilControllershowService', true],
            'App\\Controller\\EvenementController::delete' => ['privates', '.service_locator.sMofYe0.App\\Controller\\EvenementController::delete()', 'getEvenementControllerdeleteService', true],
            'App\\Controller\\EvenementController::edit' => ['privates', '.service_locator.sMofYe0.App\\Controller\\EvenementController::edit()', 'getEvenementControllereditService', true],
            'App\\Controller\\EvenementController::index' => ['privates', '.service_locator.l6hZplE.App\\Controller\\EvenementController::index()', 'getEvenementControllerindexService', true],
            'App\\Controller\\EvenementController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EvenementController::new()', 'getEvenementControllernewService', true],
            'App\\Controller\\EvenementController::show' => ['privates', '.service_locator.fcxQIzM.App\\Controller\\EvenementController::show()', 'getEvenementControllershowService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::index()', 'getLoginControllerindexService', true],
            'App\\Controller\\LoginController::logOut' => ['privates', '.service_locator.uBR2pyw.App\\Controller\\LoginController::logOut()', 'getLoginControllerlogOutService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.DQcw8Me.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.q60ydOj.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.q60ydOj.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.hKA2je_.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Controller\\AcceuilController:delete' => ['privates', '.service_locator.Vv3rbHE.App\\Controller\\AcceuilController::delete()', 'getAcceuilControllerdeleteService', true],
            'App\\Controller\\AcceuilController:edit' => ['privates', '.service_locator.Vv3rbHE.App\\Controller\\AcceuilController::edit()', 'getAcceuilControllereditService', true],
            'App\\Controller\\AcceuilController:index' => ['privates', '.service_locator.D1r9Q3..App\\Controller\\AcceuilController::index()', 'getAcceuilControllerindexService', true],
            'App\\Controller\\AcceuilController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\AcceuilController::new()', 'getAcceuilControllernewService', true],
            'App\\Controller\\AcceuilController:show' => ['privates', '.service_locator.wQtEMKU.App\\Controller\\AcceuilController::show()', 'getAcceuilControllershowService', true],
            'App\\Controller\\EvenementController:delete' => ['privates', '.service_locator.sMofYe0.App\\Controller\\EvenementController::delete()', 'getEvenementControllerdeleteService', true],
            'App\\Controller\\EvenementController:edit' => ['privates', '.service_locator.sMofYe0.App\\Controller\\EvenementController::edit()', 'getEvenementControllereditService', true],
            'App\\Controller\\EvenementController:index' => ['privates', '.service_locator.l6hZplE.App\\Controller\\EvenementController::index()', 'getEvenementControllerindexService', true],
            'App\\Controller\\EvenementController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EvenementController::new()', 'getEvenementControllernewService', true],
            'App\\Controller\\EvenementController:show' => ['privates', '.service_locator.fcxQIzM.App\\Controller\\EvenementController::show()', 'getEvenementControllershowService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::index()', 'getLoginControllerindexService', true],
            'App\\Controller\\LoginController:logOut' => ['privates', '.service_locator.uBR2pyw.App\\Controller\\LoginController::logOut()', 'getLoginControllerlogOutService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.DQcw8Me.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.q60ydOj.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.q60ydOj.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.hKA2je_.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
        ], [
            'App\\Controller\\AcceuilController::delete' => '?',
            'App\\Controller\\AcceuilController::edit' => '?',
            'App\\Controller\\AcceuilController::index' => '?',
            'App\\Controller\\AcceuilController::new' => '?',
            'App\\Controller\\AcceuilController::show' => '?',
            'App\\Controller\\EvenementController::delete' => '?',
            'App\\Controller\\EvenementController::edit' => '?',
            'App\\Controller\\EvenementController::index' => '?',
            'App\\Controller\\EvenementController::new' => '?',
            'App\\Controller\\EvenementController::show' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\LoginController::logOut' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AcceuilController:delete' => '?',
            'App\\Controller\\AcceuilController:edit' => '?',
            'App\\Controller\\AcceuilController:index' => '?',
            'App\\Controller\\AcceuilController:new' => '?',
            'App\\Controller\\AcceuilController:show' => '?',
            'App\\Controller\\EvenementController:delete' => '?',
            'App\\Controller\\EvenementController:edit' => '?',
            'App\\Controller\\EvenementController:index' => '?',
            'App\\Controller\\EvenementController:new' => '?',
            'App\\Controller\\EvenementController:show' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\LoginController:logOut' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
