<?php

namespace ContainerWlUnYtd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vv3rbHEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vv3rbHE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vv3rbHE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'acceuil' => ['privates', '.errored..service_locator.Vv3rbHE.App\\Entity\\Acceuil', NULL, 'Cannot autowire service ".service_locator.Vv3rbHE": it needs an instance of "App\\Entity\\Acceuil" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'acceuil' => 'App\\Entity\\Acceuil',
            'entityManager' => '?',
        ]);
    }
}
