<?php

namespace ContainerWlUnYtd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcceuilControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AcceuilController' shared autowired service.
     *
     * @return \App\Controller\AcceuilController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AcceuilController.php';

        $container->services['App\\Controller\\AcceuilController'] = $instance = new \App\Controller\AcceuilController();

        $instance->setContainer(($container->privates['.service_locator.8FV7jiY'] ?? $container->load('get_ServiceLocator_8FV7jiYService'))->withContext('App\\Controller\\AcceuilController', $container));

        return $instance;
    }
}
