<?php

namespace ContainerWlUnYtd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcceuilControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D1r9Q3..App\Controller\AcceuilController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D1r9Q3..App\\Controller\\AcceuilController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'acceuilRepository' => ['privates', 'App\\Repository\\AcceuilRepository', 'getAcceuilRepositoryService', true],
        ], [
            'acceuilRepository' => 'App\\Repository\\AcceuilRepository',
        ]))->withContext('App\\Controller\\AcceuilController::index()', $container);
    }
}
