<?php

namespace ContainerWlUnYtd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcceuil2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wQtEMKU.App\Entity\Acceuil' shared service.
     *
     * @return \App\Entity\Acceuil
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wQtEMKU": it needs an instance of "App\\Entity\\Acceuil" but this type has been excluded in "config/services.yaml".');
    }
}
