<?php

namespace ContainerZ3RqhLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_PXQGPF0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.PXQGPF0' shared service.
     *
     * @return \App\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserController::delete()": the $user argument is type-hinted with the non-existent class or interface: "App\\Entity\\User".');
    }
}
