<?php

namespace ContainerZ3RqhLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S47qGeEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s47qGeE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s47qGeE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored.4TetN6m', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::show()": the $user argument is type-hinted with the non-existent class or interface: "App\\Entity\\User".'],
        ], [
            'user' => '?',
        ]);
    }
}
