<?php

namespace ContainerZ3RqhLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcceuilControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wQtEMKU.App\Controller\AcceuilController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wQtEMKU.App\\Controller\\AcceuilController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'acceuil' => ['privates', '.errored..service_locator.wQtEMKU.App\\Entity\\Acceuil', NULL, 'Cannot autowire service ".service_locator.wQtEMKU": it needs an instance of "App\\Entity\\Acceuil" but this type has been excluded in "config/services.yaml".'],
        ], [
            'acceuil' => 'App\\Entity\\Acceuil',
        ]))->withContext('App\\Controller\\AcceuilController::show()', $container);
    }
}
