<?php

namespace ContainerZ3RqhLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.18gMACX.App\Controller\UserController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.18gMACX.App\\Controller\\UserController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'user' => ['privates', '.errored.dnlEYW6', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::edit()": the $user argument is type-hinted with the non-existent class or interface: "App\\Entity\\User".'],
        ], [
            'entityManager' => '?',
            'user' => '?',
        ]))->withContext('App\\Controller\\UserController::edit()', $container);
    }
}
