<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEQwnFqe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEQwnFqe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEQwnFqe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEQwnFqe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEQwnFqe\App_KernelDevDebugContainer([
    'container.build_hash' => 'EQwnFqe',
    'container.build_id' => '60f7dd14',
    'container.build_time' => 1721987846,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEQwnFqe');
