<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.c06d81d2.js',
                '/build/336.7f302f51.js',
                '/build/app.a381f546.js',
            ],
            'css' => [
                '/build/app.eaf179b0.css',
            ],
        ],
    ],
],

]];
